// @ts-check

import { tanstackConfig } from "@tanstack/eslint-config";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  ...tanstackConfig,

  {
    name: "crimeweb/ignores",
    ignores: [
      "eslint.config.js",
      // Agent worktrees are full repo checkouts; eslint 9 does not read
      // .gitignore, so they must be excluded explicitly or every file is
      // linted twice and sw.js fails to parse.
      ".claude/**",
      "prettier.config.js",
      "public/**/*.js",
      "dist/**",
      ".output/**",
      ".wrangler/**",
      ".vite-hooks/**",
      "coverage/**",
      // Generated by @tanstack/router-plugin on every build.
      "src/routeTree.gen.ts",
    ],
  },

  {
    name: "crimeweb/overrides",
    files: ["**/*.{ts,tsx}"],
    rules: {
      // Optional chaining and truthiness checks are used defensively against
      // TMDb payloads and JSON fixtures, where the types are hand-written and
      // more optimistic than the wire data. 54 of these; every one is a
      // deliberate guard.
      "@typescript-eslint/no-unnecessary-condition": "off",

      // Shadowing is intentional in the nested map/filter callbacks through
      // the matching pipeline.
      "no-shadow": "warn",

      // Async-by-contract handlers (server functions, loaders) do not always
      // await.
      "@typescript-eslint/require-await": "warn",
    },
  },

  {
    name: "crimeweb/react-hooks",
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
];
